language: node_js
node_js:
- 11

sudo: true

#before_install:
#- sudo apt-get install python-pip
#- sudo pip install --upgrade pip
#- sudo pip install s3cmd
#- curl https://rclone.org/install.sh | sudo bash

env:
  global:
  - secure: OeOWTtVlW4LaD1jhT3mEqMbnOc+Zkcmy8Y5imWJcLnj9eBM/x4swTsDGLX9si6hA/hAVkx+wbNKEahbyl1PaAMHYiDllHhTebgEgOuU5HnqKpv3BFO5h+hzGeGSUz9i4wCBMhZ3XAEqrzUA7zWxU0OfTmZ4/oB/lkubGf3ERQzQ2b+uAHU4sQNomHeQ8Zq8yGE0JjC30Z22QODIRr6bLvJhHQbDFFbjafAUJ9wCEGmqUcsEqMHICbt1qlVSYivkPTRQ/JYMz45A9TonEBFyipXdIq5hpblD02MOJaCLHaIUjv3740O0WWBJwTEY2oy/ZTBL6dFdRH02uVuoVtPAsaXfbcFMJ2Cl8fSV8uZb8B9OC6NXdVukjIV41NmE6bcpSg1qWAB1CUfWbTblNti+gJg3AHXvqOsogl5cuzBJDuKYCbmRDtiABMh1wcog6UsGtM2H2HhKNsD0FhNXENgo/4615MRcDE5/ZQ3cUn92RMb+2aK5Hv7zJ0xbx+33fVcQRu6sba4LK+B+CsF7YoVOfK623OuLUXUMOokNrlNyvniRcJBaTNfFSgvonmTMV9tEt6DPwE66goL1/cYPzcG3c21ZF7uMghE9Jbr3rBX3jxEuSAil0y8AL/jhYWFNmj2pllD5dTv5GnV3s/pZOs79BMsWEV3VvY0EZP/x6eoKZCrc=
  - secure: IrKX68dZwLUot3XBk8LfuR2rYXbmq2aMsfZcQmf6abbMJvzzt9pEx+s9LacfxcXw7v35yCbhQthJejfznxMheTYOdy8oxljCjnJ5bLE90K6PymyLAEaLCUD6KFzj0wC53Dh7ZAunYDvKMYbQo+YGYTQfvXlC2yuTTOJS4il7l8WSGFDAh0G49+grF1QaC441U4lxlt1kYpC1uDR4iN3t+a5z6CRxwBzwXnoI5cq/re2eO0VDNvC07bGtZTm1OakKPyOyc43NepdjVpp9E9ZKjbkYgFaMKSJKOCSvyCqsmzldXeLZPirrIBxZd/StG+dvO7EWkwIO3jw5z53tD8gnf4ixcl6RKtwEQpJYrpAjjuGqkhYQhVL6JSgp3uGtEPZLVIbieGMu7YpQjKhJLhE2+kfs0qiBG3GWIYegthiF30o+ehnPR770jr+QD4NalhNaf7hckMorWeXHIExyr/OnK7n/MVyPkuaIp2DzWnyAkgZCBecVuTjGXbInMo4RS5hK2Rf61/dBiCmoiB5t5i6fgKGzFBDx6EF3oxCyHn4bgGIRGRUiRupBvsnYsF1TuF4bScQXztjuunhAlgfj34kXg7fWe+Qz6X37uFSMXifmp9S9Azx5RHz9JJUfXPunh4uBR/nMMJLe+YCSG5IBTXC643aRStFZ4mBnqfYfwRPVGEY=
  - secure: aQXk7BYtpwTGPEwESzczIaNyWwwbsylELI/oge/DvBaXgHej9/LdzUTPbYd5HF1XN1gyT6Gl7NM3Ru66zDfSIVGzksoB/5czA49BrQ8LxIUunT19kznX/eig2Qv8ZsVrfOuHOAU1zzxhVgdQinKxA7On3C+rNDZexLBhOfm2xp8WXfHXuMy0Ksh2LwF2sMMjITQYyTw08Wp7IIm2+zCbODcj4Nk+heKPc3bQocCR1BiL1mgQ7rpKkiIWraDTar4YZ02YBhGnnzNjCaphuXy+5yVcEKQKFBZLih198C4Hp831KIr8s++uz/u7IQGR3zZTC8j6ZmrgOzgUOf/lccrYVXnZpiHeLCcgDqBfQRhFiCX944cBbdsESVcMINfup8HWL2EghaUxZSwvqlNfGDs/wJ+28EwF37B7rIIESBf4oAaZAjC2DXzQaaWWtS+lxEcr6M9qCQEvi0ScEDj7Ryq9QGxGelJf5mi93/br/n7e791JzCCJBWqFGs3Phg46m//fvicIkUZpjc8rFDYUyR7T939tqH0VaAUQaOFUXvV5UAqAGJhGq2f8bQQYZzjehIFRWLWuKSAlTIq9wVuVARJ86AydAbS5NrKjIAmPl7uTkWgGAWEmfYVlZkbs2RbxDQucdcgAa57y+pbnB9uOOS/THvB7XDl5xbPXdUIYJudOFNQ=

#stages:
#- test
#- release

before_script: curl https://rclone.org/install.sh | sudo bash

jobs:
  include:
  - name: dev
    if: (branch = master) or (tag =~ ^v)
    script:
    - set -e
    - npm run lint
    - npm run test
    - npm run build
    - rclone copy dist :s3://payone/sdk/dev/ --s3-access-key-id="$S3_ACCESS_KEY" --s3-endpoint=$S3_HOST --s3-secret-access-key="$S3_SECRET_KEY"
    - npm run coverage:publish
  - name: release
    if: (tag =~ ^v)
    script:
    - set -e
    - npm run lint
    - npm run test
    - npm run build
    - rclone copy dist :s3://payone/sdk/latest/ --s3-access-key-id="$S3_ACCESS_KEY" --s3-secret-access-key="$S3_SECRET_KEY" --s3-endpoint=$S3_HOST
    - rclone copy dist :s3://payone/sdk/$TRAVIS_TAG/ --s3-access-key-id="$S3_ACCESS_KEY" --s3-secret-access-key="$S3_SECRET_KEY" --s3-endpoint=$S3_HOST

notifications:
  email: false
  slack:
    secure: EfqPW3dwulj/+GsA3mMSTEAJGkt9XJ0YiapBHiiyfoVg0YToqto8st5LcJAhmQ+5XPyvnZ5fyZmOFQbYdLSV4JoZDx5AspObe2C0rM7mcdYA9JzTxseOr48XagZH2KOtf5+fgVuCANmfrxTv2xZAGC37hX9/YFdunG3SEvfmc1j1mSmwQqwDChsEDET6XzcgA/Q3tplLNcfLKXf2j4GR0Y1Lc+E6lsnRmRXeDVW6R9hI4rcfkCeSy+vWzAaa31t9i+O4zxZGcCxlTxKcbDVpBidCfu3pasbAjf+CCApfFNzEWRrfD7Wx77nrbdrUpta663YYB2gqU9/6dVLHbRCZIJMzc5KmAtrdxFC4kSf0V+g72oUXPe/0F6VxhJR68ymW8JZvWuiWCmfVqR4t3O90S1BXlL2Ccw5YOGs1NID6ZiPNn4XYBGp8LGpSqPgq/XCmJQgwYb7+ASZAj+P5EOjTrEHZJ01n/jxgRsmGxq6MYlFSywfeVxgRLL5ZJSTj1u05s+UadYtrUD6dN3dJaX+j5ZN/x4Su1FbT8KFKYzNmabQH9ireNzdvfZJkSPpxC1IByRB7LZWvDNCce0kCmqvBP9r7XVmRp7UNPIr2Zxyghq/6wGfxMTqZUN3vgJIqBwm+NumjbyIhAFFavBcRXlelVmL+khpNMof6X/DJ3n7fbG0=